In [1]:
import torch
from torch import nn

In [2]:
torch.manual_seed(123) 
batch_example = torch.randn(2, 5) 
layer = nn.Sequential(nn.Linear(5, 6), nn.ReLU()) 
out = layer(batch_example) 
print(out)

tensor([[0.2260, 0.3470, 0.0000, 0.2216, 0.0000, 0.0000],
        [0.2133, 0.2394, 0.0000, 0.5198, 0.3297, 0.0000]],
       grad_fn=<ReluBackward0>)


In [5]:
ln = nn.LayerNorm(normalized_shape=5, eps = 1e-5)
out_ln = ln(batch_example) 
mean = out_ln.mean(dim=-1, keepdim=True) 
var = out_ln.var(dim=-1, unbiased=False, keepdim=True) 
torch.set_printoptions(sci_mode=False)
print("Mean:\n", mean) 
print("Variance:\n", var)

Mean:
 tensor([[-0.0000],
        [ 0.0000]], grad_fn=<MeanBackward1>)
Variance:
 tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)
